require "helpers/database_helpers"

RSpec.describe "Cat Ads Feature", type: :feature do
  before(:each) do
    DatabaseHelpers.clear_table("cat_ads")
    DatabaseHelpers.clear_table("users")
  end

  it "signs up user and shows profile page" do
    visit "/users/signup"
    fill_in "Name:", with: "Tom Jones"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Mobile:", with: "0123456789"
    fill_in "Password:", with: "1234"
    click_button "Save"
    expect(page).to have_content "Profile"
    expect(page).to have_content "tomjones@gmail.com"
  end

  it "logs in and logs out showing the correct menu" do
    visit "/users/signup"
    fill_in "Name:", with: "Tom Jones"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Mobile:", with: "0123456789"
    fill_in "Password:", with: "1234"
    click_button "Save"
    click_link "Log Out"
    expect(page).to have_content "Log In"
    click_link "Log In"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Password:", with: "1234"
    click_button "Log In"
    expect(page).to have_content "Add Missing Cat Ad"
    click_link "Log Out"
    expect(page).not_to have_content "Add Missing Cat Ad"
    expect(page).to have_content "Log In"
  end

  it "starts with an empty list of ads" do
    visit "/catboard"
    expect(page).to have_content "There are no ads to show."
  end

  it "adds and lists missing cat ads" do
    visit "/users/signup"
    fill_in "Name:", with: "Tom Jones"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Mobile:", with: "0123456789"
    fill_in "Password:", with: "1234"
    click_button "Save"
    click_link "Log Out"
    expect(page).to have_content "Log In"
    click_link "Log In"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Password:", with: "1234"
    click_button "Log In"
    visit "/catboard"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing persian"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: "image_url"
    click_button "Add Missing Cat Ad"
    expect(page).to have_content "Missing persian"
  end

  it "adds and lists multiple ads" do
    visit "/users/signup"
    fill_in "Name:", with: "Tom Jones"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Mobile:", with: "0123456789"
    fill_in "Password:", with: "1234"
    click_button "Save"
    click_link "Log Out"
    expect(page).to have_content "Log In"
    click_link "Log In"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Password:", with: "1234"
    click_button "Log In"
    visit "/catboard"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing persian"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing aegean"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing moggie"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"
    expect(page).to have_content "Missing persian"
    expect(page).to have_content "Missing aegean"
    expect(page).to have_content "Missing moggie"
  end

  it "deletes ads" do
    visit "/users/signup"
    fill_in "Name:", with: "Tom Jones"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Mobile:", with: "0123456789"
    fill_in "Password:", with: "1234"
    click_button "Save"
    click_link "Log Out"
    expect(page).to have_content "Log In"
    click_link "Log In"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Password:", with: "1234"
    click_button "Log In"
    visit "/catboard"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing persian"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing aegean"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing moggie"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"

    find('section[id="Missing persian"]').click_button "Delete"

    expect(page).to have_content "Missing aegean"
    expect(page).not_to have_content "Missing persian"
    expect(page).to have_content "Missing moggie"
  end

  it "updates ads" do
    visit "/users/signup"
    fill_in "Name:", with: "Tom Jones"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Mobile:", with: "0123456789"
    fill_in "Password:", with: "1234"
    click_button "Save"
    click_link "Log Out"
    expect(page).to have_content "Log In"
    click_link "Log In"
    fill_in "Email:", with: "tomjones@gmail.com"
    fill_in "Password:", with: "1234"
    click_button "Log In"
    visit "/catboard"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing persian"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing aegean"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"
    click_link "Add Missing Cat Ad"
    fill_in "Title", with: "Missing moggie"
    fill_in "Description", with: "Special cat gone missing!"
    fill_in "Image URL", with: ""
    click_button "Add Missing Cat Ad"

    find('section[id="Missing persian"]').click_link "Edit"
    fill_in "Title", with: "Missing siamese"
    click_button "Update Cat Ad"

    expect(page).to have_content "Missing siamese"
    expect(page).not_to have_content "Missing persian"
    expect(page).to have_content "Missing aegean"
    expect(page).to have_content "Missing moggie"
  end
end
